import type { Item, Rope, WallpaperType } from './types';

/** 默认墙名 */
export const DEFAULT_WALL_NAME = 'Wall 01';
export const DEFAULT_WALL_ID = 'wall-first-mind';
export const DEFAULT_WALLPAPER: WallpaperType = 'cream';

/** 样例图片 Item 配置（引用 manifest.json 中的 asset ID） */
export const INITIAL_PICTURE_ITEMS: Item[] = [
  {
    id: 'item-pic-north-01',
    type: 'picture',
    x: 80,
    y: 60,
    width: 200,
    height: 150,
    rotation: -2,
    assetId: 'north-01-wat-chedi-luang',
    pinOffset: { x: 0.5, y: 0 },
  },
  {
    id: 'item-pic-north-02',
    type: 'picture',
    x: 340,
    y: 40,
    width: 160,
    height: 213,
    rotation: 1.5,
    assetId: 'north-02-khao-soi',
    pinOffset: { x: 0.5, y: 0 },
  },
  {
    id: 'item-pic-north-03',
    type: 'picture',
    x: 560,
    y: 50,
    width: 160,
    height: 213,
    rotation: -1,
    assetId: 'north-03-white-temple',
    pinOffset: { x: 0.5, y: 0 },
  },
  {
    id: 'item-pic-bangkok-01',
    type: 'picture',
    x: 120,
    y: 340,
    width: 160,
    height: 213,
    rotation: 2,
    assetId: 'bangkok-01',
    pinOffset: { x: 0.5, y: 0 },
  },
  {
    id: 'item-pic-bangkok-02',
    type: 'picture',
    x: 360,
    y: 330,
    width: 160,
    height: 213,
    rotation: -1.5,
    assetId: 'bangkok-02',
    pinOffset: { x: 0.5, y: 0 },
  },
  {
    id: 'item-pic-bangkok-03',
    type: 'picture',
    x: 580,
    y: 350,
    width: 180,
    height: 135,
    rotation: 1,
    assetId: 'bangkok-03',
    pinOffset: { x: 0.5, y: 0 },
  },
];

/** 样例 Paper Item 配置 */
export const INITIAL_PAPER_ITEMS: Item[] = [
  // 标题卡（storytelling 起点：整面墙的主题）
  {
    id: 'item-paper-title',
    type: 'paper',
    variant: 'note',
    x: 330,
    y: -110,
    width: 220,
    height: 70,
    rotation: -1,
    text: 'Thailand Trip — Chiang Mai & Bangkok',
    pinOffset: { x: 0.5, y: 0 },
  },
  // 普通纸 note
  {
    id: 'item-paper-note-01',
    type: 'paper',
    variant: 'note',
    x: 100,
    y: 240,
    width: 160,
    height: 80,
    rotation: -3,
    text: 'The quiet of Wat Chedi Luang makes me not want to leave',
    pinOffset: { x: 0.5, y: 0 },
  },
  {
    id: 'item-paper-note-02',
    type: 'paper',
    variant: 'note',
    x: 320,
    y: 280,
    width: 170,
    height: 80,
    rotation: 2,
    text: 'Khao Soi — the soul curry noodles of Northern Thailand',
    pinOffset: { x: 0.5, y: 0 },
  },
  {
    id: 'item-paper-note-03',
    type: 'paper',
    variant: 'note',
    x: 540,
    y: 290,
    width: 180,
    height: 80,
    rotation: -1,
    text: 'The White Temple is breathtaking in person',
    pinOffset: { x: 0.5, y: 0 },
  },
  // 撕边纸 torn
  {
    id: 'item-paper-torn-01',
    type: 'paper',
    variant: 'torn',
    x: 100,
    y: 590,
    width: 170,
    height: 90,
    rotation: 1.5,
    text: 'Rainbow after rain at Siam Square',
    pinOffset: { x: 0.5, y: 0 },
  },
  {
    id: 'item-paper-torn-02',
    type: 'paper',
    variant: 'torn',
    x: 320,
    y: 580,
    width: 180,
    height: 90,
    rotation: -2,
    text: 'Can not stop buying samples at 7-11',
    pinOffset: { x: 0.5, y: 0 },
  },
  {
    id: 'item-paper-torn-03',
    type: 'paper',
    variant: 'torn',
    x: 550,
    y: 570,
    width: 170,
    height: 90,
    rotation: 1,
    text: 'Thai people take fragrance to the extreme',
    pinOffset: { x: 0.5, y: 0 },
  },
  // 便利贴 sticky
  {
    id: 'item-paper-sticky-01',
    type: 'paper',
    variant: 'sticky',
    x: 760,
    y: 100,
    width: 120,
    height: 120,
    rotation: 4,
    text: 'Must go back to Chiang Mai!',
    color: '#fef08a',
    pinOffset: { x: 0.5, y: 0 },
  },
  {
    id: 'item-paper-sticky-02',
    type: 'paper',
    variant: 'sticky',
    x: 780,
    y: 260,
    width: 120,
    height: 120,
    rotation: -3,
    text: 'First step in Thai: sawatdee',
    color: '#bbf7d0',
    pinOffset: { x: 0.5, y: 0 },
  },
  // 胶带 tape
  {
    id: 'item-paper-tape-01',
    type: 'paper',
    variant: 'tape',
    x: 200,
    y: 30,
    width: 80,
    height: 24,
    rotation: -5,
    color: 'rgba(255,255,255,0.6)',
  },
  {
    id: 'item-paper-tape-02',
    type: 'paper',
    variant: 'tape',
    x: 430,
    y: 25,
    width: 80,
    height: 24,
    rotation: 3,
    color: 'rgba(255,255,255,0.6)',
  },
  {
    id: 'item-paper-tape-03',
    type: 'paper',
    variant: 'tape',
    x: 640,
    y: 35,
    width: 80,
    height: 24,
    rotation: -2,
    color: 'rgba(255,255,255,0.6)',
  },
];

/** 样例 Stamp Item 配置 */
export const INITIAL_STAMP_ITEMS: Item[] = [
  {
    id: 'item-stamp-01',
    type: 'stamp',
    x: 130,
    y: 180,
    width: 60,
    height: 60,
    rotation: -8,
    stampId: 'stamp-blue-travel',
    parentId: 'item-paper-note-01',
    pinOffset: { x: 0.5, y: 0.5 },
  },
  {
    id: 'item-stamp-02',
    type: 'stamp',
    x: 580,
    y: 230,
    width: 60,
    height: 60,
    rotation: 5,
    stampId: 'stamp-red-passport',
    parentId: 'item-paper-note-03',
    pinOffset: { x: 0.5, y: 0.5 },
  },
  {
    id: 'item-stamp-03',
    type: 'stamp',
    x: 370,
    y: 530,
    width: 60,
    height: 60,
    rotation: -3,
    stampId: 'stamp-green-nature',
    parentId: 'item-paper-torn-02',
    pinOffset: { x: 0.5, y: 0.5 },
  },
];

/** 所有初始 Item */
export const INITIAL_ITEMS: Item[] = [
  ...INITIAL_PICTURE_ITEMS,
  ...INITIAL_PAPER_ITEMS,
  ...INITIAL_STAMP_ITEMS,
];

/** 样例 Rope 连接（形成完整 storytelling：标题 → 北线 → 曼谷线） */
export const INITIAL_ROPES: Rope[] = [
  {
    id: 'rope-title-north',
    fromItemId: 'item-paper-title',
    toItemId: 'item-pic-north-01',
    note: 'North begins',
    naturalLength: 260,
  },
  {
    id: 'rope-title-bangkok',
    fromItemId: 'item-paper-title',
    toItemId: 'item-pic-bangkok-01',
    note: 'Then Bangkok',
    naturalLength: 520,
  },
  {
    id: 'rope-01',
    fromItemId: 'item-pic-north-01',
    toItemId: 'item-paper-note-01',
    note: 'Thoughts on Wat Chedi Luang',
    naturalLength: 200,
  },
  {
    id: 'rope-02',
    fromItemId: 'item-pic-north-02',
    toItemId: 'item-paper-note-02',
    note: 'Khao Soi notes',
    naturalLength: 180,
  },
  {
    id: 'rope-03',
    fromItemId: 'item-pic-north-03',
    toItemId: 'item-paper-note-03',
    note: 'White Temple impressions',
    naturalLength: 190,
  },
  {
    id: 'rope-04',
    fromItemId: 'item-pic-bangkok-01',
    toItemId: 'item-paper-torn-01',
    note: 'Siam Square',
    naturalLength: 250,
  },
  {
    id: 'rope-05',
    fromItemId: 'item-pic-bangkok-02',
    toItemId: 'item-paper-torn-02',
    note: '7-11 finds',
    naturalLength: 230,
  },
  {
    id: 'rope-06',
    fromItemId: 'item-pic-bangkok-03',
    toItemId: 'item-paper-torn-03',
    note: 'Bangkok nights',
    naturalLength: 240,
  },
];
